
/**
 * Write a description of class circumference_area_of_circle here.
 *
 * @author (1337mickey)
 * @version (a version number or a date)
 */
public class circumference_area_of_circle
{
    public static void main(String[] args) {
        int r;
        float perimeter;
        float area;
        r=7;
        
        perimeter = 2 * 3.14f * r;
        area = 3.14f * r * r;
        System.out.println(perimeter);
        System.out.println(area);
         }
}
