
/**
 * Write a description of class distance_covered_by_body here.
 *
 * @author (1337mickey)
 * @version (a version number or a date)
 */
public class distance_covered_by_body
{
    public static void main(String[] agrs) {
        int u,t,a;
        float distance;
        
        a=1;
        u=5;
        t=3;
        distance = u*t+(0.5f * a* t* t);
        
        System.out.println(distance);
    
        
    
    }
}
