
/**
 * Write a description of class peremeter_of_rectangle here.
 *
 * @author (1337mickey)
 * @version (a version number or a date)
 */
public class peremeter_of_rectangle
{
    public static void main(String[] args)
    { 
         int l,b;
  int peremeterofrectangle;
  
  l = 6;
  b = 7;
  peremeterofrectangle = 2 * (l+b);
  System.out.println(peremeterofrectangle);
    }
 
  
}

    